apiVersion: v1
kind: ConfigMap
metadata:
  name: etcd-backup-script
  namespace: monitoring
data:
  etcd-backup.sh: |
    #!/bin/bash
    export ETCDCTL_API=3
    DATE=$(date +%Y%m%d_%H%M)
    BACKUP_DIR="/data/etcd-backup"
    BACKUP_FILE="${BACKUP_DIR}/etcd-${DATE}.db"
    
    ETCDCTL_CMD="etcdctl --endpoints=https://127.0.0.1:2379 --cacert=/etc/ssl/etcd/ssl/ca.pem --cert=/etc/ssl/etcd/ssl/admin-node1.pem --key=/etc/ssl/etcd/ssl/admin-node1-key.pem"
    
    echo "etcd 백업 시작..."
    $ETCDCTL_CMD snapshot save ${BACKUP_FILE} > /dev/null 2>&1
    
    if [ $? -eq 0 ]; then
      $ETCDCTL_CMD --write-out=simple snapshot status ${BACKUP_FILE} > /dev/null 2>&1
      if [ $? -eq 0 ]; then
        echo "백업 성공: ${BACKUP_FILE}"
        curl -s -X POST -H 'Content-type: application/json' --data '{"text":"[node1] etcd GitOps 자동 백업 성공!"}' ${WEBHOOK_URL}
      else
        curl -s -X POST -H 'Content-type: application/json' --data '{"text":"[node1] etcd 백업 파일 손상!"}' ${WEBHOOK_URL}
      fi
    else
      curl -s -X POST -H 'Content-type: application/json' --data '{"text":"[node1] etcd 백업 실패!"}' ${WEBHOOK_URL}
    fi
    
    # 14일 지난 백업 자동 삭제
    find ${BACKUP_DIR} -name "etcd-*.db" -type f -mtime +14 -delete
    echo "오래된 백업 정리 완료."
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: etcd-backup-job
  namespace: monitoring
spec:
  schedule: "0 3 * * *" # 매일 새벽 3시
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          hostNetwork: true #  127.0.0.1(호스트 etcd) 접근 허용
          nodeSelector:
            node-role.kubernetes.io/control-plane: "" # 무조건 마스터 노드에서만 실행
          tolerations:
            - key: node-role.kubernetes.io/control-plane
              operator: Exists
              effect: NoSchedule
          containers:
          - name: backup-container
            image: ubuntu:22.04 # etcdctl이 포함된 이미지 사용
            command: 
                - /bin/bash
                - -c
                - |
                  apt-get update -y && apt-get install -y etcd-client curl
                  /bin/bash /scripts/etcd-backup.sh
            securityContext:
                runAsUser: 0 # root 권한 (인증서 읽기 및 백업 폴더 쓰기 위함)
            env:
              - name: WEBHOOK_URL   # 스크립트의 $WEBHOOK_URL 변수에 값이 들어갑니다.
                valueFrom:
                  secretKeyRef:
                    name: etcd-backup-secret # 복호화된 일반 Secret 이름
                    key: WEBHOOK_URL
            volumeMounts:
                - name: script-volume
                  mountPath: /scripts
                - name: etcd-certs
                  mountPath: /etc/ssl/etcd/ssl
                  readOnly: true
                - name: backup-dir
                  mountPath: /data/etcd-backup
          restartPolicy: OnFailure
          volumes:
            - name: script-volume
              configMap:
                name: etcd-backup-script
            - name: etcd-certs
              hostPath:
                path: /etc/ssl/etcd/ssl
                type: Directory
            - name: backup-dir
              hostPath:
                path: /data/etcd-backup
                type: DirectoryOrCreate
