apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: etcd-backup-secret
  namespace: monitoring
spec:
  encryptedData:
    # 아래 값은 클러스터 공개키 암호화된 값 
    WEBHOOK_URL: AgB5iG/OFwIU9lSMvKuVJfe9Za8AFce6PjD7S0XlDavAL4YHA1mabUkWGPATCIlrLEUWpYpfaLl8k77ullK4+HR428lXwz/TCHEGRVMOZaDR4ZMAxQwjOF0EzseADM/e4XWaobRfmKYq55nxSHWnm8qhyH6IcmAgwXumCjRgy629KSAGbRnGzhSU5xAjtMNKVgiWt1ZU4dxa6PBX0MKaUhAbxdLddFh1Oyc5P1K6WqsjxD6sD+PT2Av7AmNTiVStQsSYIo8tJsNdGa9vwNSgh/fhEp/7IHbf/oXfqF+m52bxnS88k7tK2P6pdkK5+PA6R78/2JIvOW+tzSR6j6em11y+/zf7dASK3JB4wDTqglyGcUA+8QIHWfVU8TyWUfDjltGwn/p76Vq6keOvsLOPsJTnYPZqmcj5vVY/DkXABbcZT12GPWdKlCTM5Ftfgu/ezaUvIjSEE9e0zg0+mX6UU8HnqV3DDUz5aA8xXrTK2g3B5GyIu4fEtlPeXdJy4R/n5U6fGWs7u3ULnZLEhDeJB6DVSbx8eICUntkD2l5XZHB6/tAKZDhAiI+TLzMrytLJY/AA6j/9C+jZjaHN68mwn5iLirohrvlqeHrJsJEo2kwzqwYWD9ENAWBLM0T33nINZcIU5B1RKr/+kWmHLRt3wvytDhpffOnISUrcjvrg9OmSY65mKAKdQGW9J37heAScwb/uNndtN4wfgfayDauqjed6GpUN64I5Y0g2NEXIBHeYuFN+QOWgNPmE+dslU4TOszeADUY2S+oGWU5wsA4Ys39EoC8YPJ0e8ZEuzZiz4a9vqIg=
  template:
    metadata:
      name: etcd-backup-secret
    type: Opaque
