apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-auth-secret
  namespace: monitoring
spec:
  encryptedData:
    # 아래 값은 클러스터 공개키 암호화된 값 
    userKey: AgBeuwd2DJPEbX/zM6HTCd5uaDnE/qFZCnqTpPvHrT6lcSTNHbT3vMdh2tcusSpPKbsWOdaQoqinZJKGbUS1dZY+2N7FHExoa7GgkyhlksHuTrUDXF5B+J+R93AobhrlkPo/e9HTJ+VaPGKAz00JNsacUJQ96grOYgFcACe4w2FrKiTkw8JbkZRpfX6nvW2ZY8KEIRVdOru5ybjkMeicFN2nYngVngUSfD3YgltbVux4X8jsSBvM/yZ5qE1Ldzn/+VTIE1vXrJpRouuktuv6NQjDtFsbFsE1mEm+ZiE39zmXBgOzcCVmdqVLZelsQAsy/95dT4VqocW1gg0H0uAK1omQ108vkpX8vXG2GGIdwSdTFCHhjtMfEQjU7bfh2UzLqhPmgsfru3KTNCtLwUn2MXoF7/6HwVw6erThbEewqDQ3OQTrTqQ4kegaPkHY8WS8E6YDsDE5jbrLrkgGTwE9cIcvXJ6XU+TMP+0eNRmAqX0evWYzLaQR2PDIT2QBUJyFerFq7hkK5hVWW1RNqv+bp8kLR3yNyBfQEfvFGWA3valTHH7dbS4AW5bjsHWXYkzb8HdRiar3hdWU8T2qNtMJUxD9ky3UawqRXvPsu73cXd3QuzxuudvckQNzSF049JrHW2Gu8iMk9OVf65h3VtjljiPqUBIQx9B35yGMCLxABRSoLa/enSANHtAa8ufOY3IkikQNte8l4Q==
    passwordKey: AgBZSk3QYITTx2AhvBSf1zUm1Nc1Twq8MnRG8QdCi3hmYsiw5yfDm547jOX2EiBJbq9SaARwjx3zGnWfrvzJ4SqFrC0j+/66aSviu9K0wd+dfTTZ4KAkgUN7hvgUkz9cUmjDeBoeyp1qzJzJmj4eQa96bsuZJfiU0j2x2wMUK7d0XEQdYi7/T7v6RvMw+imt6j/8In6fBCTQYuWnYsFVnWycsb6WrQhUCCNWAN9vDWGqzfhHScKzVqKznk7VSwM5r7BqRYbtm8zKa6DC/X0XCQbnj00kih628DwGoB5+JpRE1dcDcYAbsSjUzP994x6htBV0AzFYPHF+x/mdh3+NWHSVnQarrAXJ+aMpy4zk1g6Cu6T81ReAwTK0yncOR+5YAwQYX5izcfbdBdrFLo8JGFr2iGZq32vJBMeuq6Q6Rjd0BrQYN67zQNEvIHBR0sQ5sRL3TqzGymo2d5mMwtL/0yCPqgYGIpiVk/iM15nGa6MkFEENYtoF3r0W7QmK00cx+/MLGehf44u713R8MYnFwnTQ7Sup/tc3BVer/YkZJKhFr2km+Zk0XnpkPMNvliqPjIm/ZhvNpfUayn9jwfhJqXN5XKecCIPxl/KV5E75Jdq2n17ElcsNet9u3gWaMC1EMbRDBRmcUDiobZGlklEIqkdnxu9qV4ClpoNrxH9G+jSc0tyIcpX/Zx2OtSYyIGDp73p0FWzSIq6avdzqMtCusg==
  template:
    metadata:
      name: grafana-auth-secret
    type: Opaque
